CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Models/Application.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CommunityProject_ProjectUnity.Models
{
    public class Application : Auditable
    {
        public Application()
        {
            this.Files = new HashSet<ApplicationFiles>();
            this.UserFiles = new HashSet<aFile>();
        }
       
           
        public int ID { get; set; }

        [Display(Name = "Covering Comments")]
        [Required(ErrorMessage = "You cannot leave the summary comments blank.")]
        [StringLength(2000, ErrorMessage = "Summary must be between 20 and 2000 characters", MinimumLength = 20)]
        [DataType(DataType.MultilineText)]
        public string Comments { get; set; }

        [Required(ErrorMessage = "You must specify the job posting applied for.")]
        [Index("IX_Unique_Application", Order = 1, IsUnique = true)]
        public int PostingID { get; set; }

        [Required(ErrorMessage = "You must specify the applicant applying to the job posting.")]
        [Index("IX_Unique_Application", Order = 2)]
        public int ApplicantID { get; set; }

       
        public virtual ICollection<ApplicationFiles> Files { get; set; }

        public virtual ICollection<aFile> UserFiles { get; set; }

        public virtual Posting Posting { get; set; }

        [Display(Name = "Application Status")]
        public string Applicationstatus { get; set; }
        

        public virtual Applicant Applicant { get; set; }
    }
}

CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CommunityProject_ProjectUnity.DAL;
using CommunityProject_ProjectUnity.Models;
using CommunityProject_ProjectUnity.ViewModels;
using Microsoft.AspNet.Identity;
using Rotativa;

namespace CommunityProject_ProjectUnity.Controllers
{
   
    public class ApplicationsController : Controller
    {
        private ProjectUnityEntities db = new ProjectUnityEntities();

        // GET: Applications
        public ActionResult Index()
        {
            var applications = db.Applications.Include(a => a.Applicant).Include(a => a.Posting);
            if (!User.IsInRole("Admin"))
            {
                  applications = db.Applications.Include(a => a.Applicant).Include(a => a.Posting)
                                              .Where(a => a.CreatedBy == User.Identity.Name);
            }
            
                
            return View(applications.ToList());
        }
        public ActionResult SelectedApplications()
        {
            var applications = db.Applications.Where(a => a.Applicationstatus == "Selected");
            return View(applications.ToList());
        }
        // GET: Applications/Details/5
        public ActionResult Details(int? id)
        {
            var userfiles = db.AppFiles.Where(a => a.ApplicationID == id);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            var postingID = application.PostingID;
            if (application == null)
            {
                return HttpNotFound();
            }
            ViewBag.Files = userfiles.ToList();

            var skills = application.Applicant.Skills;
            //ViewBag.SkillsList = skills.ToList();
            return View(application);
        }

        // GET: Applications/Create
        public ActionResult Create(int?id)
        {
            var application = new Application();
            int userID = db.Applicants
                       .Where(q => q.Email==User.Identity.Name.ToString())
                       .Select(q => q.ID)
                       .FirstOrDefault();
            Posting posting = db.Postings.Find(id);
            string posname = posting.Name;
            var userfiles = db.Files.Where(a => a.ApplicantID == userID);
            ViewBag.ApplicantID = userID;
            ViewBag.PostingName = posname;
            //ViewBag.City = posting.City.Name;
            ViewBag.PostingID = id;
            //ViewBag.School = posting.School.Name;
            ViewBag.Desc = posting.Description;
            PopulateUserFileData(application);
            var poschools = posting.Schools.ToList();
            ViewBag.Schools = poschools;
            return View();
        }

        // POST: Applications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Comments,PostingID,ApplicantID,CreatedBy,CreatedOn,UpdatedBy,UpdatedOn,RowVersion")] Application application, string [] selectedFiles,
            IEnumerable<HttpPostedFileBase> Attachments)
        {
            if (ModelState.IsValid)
            {
                //Add the selected skills
                if (selectedFiles != null)
                {
                    application.UserFiles = new List<aFile>();
                    foreach (var file in selectedFiles)
                    {
                        var FileToAdd = db.Files.Find(int.Parse(file));
                        application.UserFiles.Add(FileToAdd);
                    }
                }
                AddDocuments(ref application, Attachments);
                db.Applications.Add(application);
                db.SaveChanges();
                return RedirectToAction("Details", "Applicants");
            }

            //ViewBag.ApplicantID = new SelectList(db.Applicants, "ID", "FirstName", application.ApplicantID);
            //ViewBag.PostingID = new SelectList(db.Postings, "ID", "Name", application.PostingID);
            return View(application);
        }

        // GET: Applications/Edit/5
        public ActionResult Edit(int? id)
        {
            int userID = db.Applicants
                      .Where(q => q.Email == User.Identity.Name.ToString())
                      .Select(q => q.ID)
                      .FirstOrDefault();
            int postid = db.Applications
                           .Where(p => p.ID == id)
                           .Select(q => q.PostingID)
                           .FirstOrDefault();
            var userfiles = db.Files.Where(a => a.ApplicantID == userID);
            Posting posting = db.Postings.Find(postid);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            //ViewBag.ApplicantID = new SelectList(db.Applicants, "ID", "FirstName", application.ApplicantID);
            //ViewBag.PostingID = new SelectList(db.Postings, "ID", "Name", application.PostingID);
            ViewBag.ApplicantID = userID;
            ViewBag.PostingID = postid;
            ViewBag.PostingName = posting.Name;
            ViewBag.Desc = posting.Description;
            var poschools = posting.Schools.ToList();
            ViewBag.Schools = poschools;
            ViewBag.Files = userfiles.ToList();
            ViewBag.ApplicationStatus = new SelectList(ApplicationStatus, "Value", "Text", application?.Applicationstatus);
            return View(application);
        }

        // POST: Applications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
         [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
       
        public ActionResult EditPost(int? id, Byte[] rowVersion, IEnumerable<HttpPostedFileBase> Attachments)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           
            var applicationToUpdate = db.Applications
                                        .Include(a => a.Files)
                                        .Where(p => p.ID == id).SingleOrDefault();
            //AddDocuments(ref applicationToUpdate, Attachments);
            if (TryUpdateModel(applicationToUpdate, "",
              new string[] { "Comments", "PostingID", "ApplicantID", "Applicationstatus" }))
            {
                try
                {
                    db.Entry(applicationToUpdate).OriginalValues["RowVersion"] = rowVersion;
                    db.SaveChanges();
                    return RedirectToAction("Index");

                }
                catch (RetryLimitExceededException /* dex */)
                {
                    ModelState.AddModelError("", "Unable to save changes after multiple attempts. Try again, and if the problem persists, see your system administrator.");
                }
                catch (DbUpdateConcurrencyException ex)// Added for concurrency
                {
                    var entry = ex.Entries.Single();
                    var clientValues = (Application)entry.Entity;
                    var databaseEntry = entry.GetDatabaseValues();
                    if (databaseEntry == null)
                    {
                        ModelState.AddModelError("",
                            "Unable to save changes. The Posting was deleted by another user.");
                    }
                    else
                    {
                        var databaseValues = (Application)databaseEntry.ToObject();
                        
                        
                        if (databaseValues.Comments != clientValues.Comments)
                            ModelState.AddModelError("Comments", "Current value: "
                                + databaseValues.Comments);
                        
                        ModelState.AddModelError(string.Empty, "The record you attempted to edit "
                                + "was modified by another user after you received your values. The "
                                + "edit operation was canceled and the current values in the database "
                                + "have been displayed. If you still want to save your version of this record, click "
                                + "the Save button again. Otherwise click the 'Back to List' hyperlink.");
                        applicationToUpdate.RowVersion = databaseValues.RowVersion;
                    }
                }
                catch (DataException)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                }
            }
            ViewBag.ApplicationStatus = new SelectList(ApplicationStatus, "Value", "Text", applicationToUpdate?.Applicationstatus);
            return View(applicationToUpdate);
        }
        //ViewBag.ApplicantID = new SelectList(db.Applicants, "ID", "FirstName", application.ApplicantID);
        //ViewBag.PostingID = new SelectList(db.Postings, "ID", "Name", application.PostingID);


        List<SelectListItem> ApplicationStatus = new List<SelectListItem>()
            {

CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Views/Applications/Create.cshtml
@model CommunityProject_ProjectUnity.Models.Application

@{
    ViewBag.Title = "Create";
}




@using (Html.BeginForm("Create", "Applications", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="horizontal">
    <div class="row">
        <h2>Create Application</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <input type="hidden" name="ApplicantID" value="@ViewBag.ApplicantID" />
        <input type="hidden" name="PostingID" value="@ViewBag.PostingID" />

        <div class="form-group">
             <div class="col-lg-6 col-md-6 col-sm-10 col-xs-1">
                 @Html.LabelFor(model => model.Posting.Name, htmlAttributes: new { @class = "control-label col-lg-3 col-md-3 col-sm-8 col-xs-12" })
                 <div class="col-lg-5 col-md-5 col-sm-10 col-xs-12">
                    <label>@ViewBag.PostingName</label>
                 </div>
             </div>
        </div>
        <div class="form-group">
            <div class="col-lg-6 col-md-6 col-sm-10 col-xs-12">
                @Html.LabelFor(model => model.Posting.Schools, htmlAttributes: new { @class = "control-label col-lg-3 col-md-3 col-sm-8 col-xs-12" })
                <div class="col-lg-9 col-md-5 col-sm-10 col-xs-12">
                    <div class="well">
                        @foreach (var school in ViewBag.Schools)
                        {
                            @school.Name<br />
                        }
                    </div>
                </div>
            </div>
        </div>   
        <div class="form-group">
            <div class="col-lg-6 col-md-6 col-sm-10 col-xs-12">
                @Html.LabelFor(model => model.Posting.Description, htmlAttributes: new { @class = "col-lg-3 col-md-3 col-sm-8 col-xs-12" })
                <label class="control-label col-lg-5 col-md-3 col-sm-8 col-xs-12">@ViewBag.Desc</label>
            </div>
        </div>
       
        <div class="form-group">
            <div class="col-lg-6 col-md-6 col-sm-10 col-xs-12">
                @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "col-lg-3 col-md-3 col-sm-8 col-xs-12" })
                <label class="control-label col-md-7">
                    @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
                </label>
            </div>
        </div>
    
         <div class="form-group"> 
            <div class="col-lg-6 col-md-6 col-sm-10 col-xs-12">
            <label class="control-label col-lg-3 col-md-3 col-sm-8 col-xs-12">Current Documents in Profile</label>
                <table>
                    <tr>                 
                       @{
                            int cnt = 0;
                            List<CommunityProject_ProjectUnity.ViewModels.AssignedUserFilesVM> files = ViewBag.Files;
                            foreach (var file in files)
                            {
                                if (cnt++ % 3 == 0)
                                {
                                    @:</tr><tr>
                                }
                                @:<td>
                                <br/>
                                <label class="control-label">
                                    <input type="checkbox" name="selectedFiles" value="@file.FileID" @(Html.Raw(file.Assigned ? "checked=\"checked\"" : "")) />
                                    @file.FileName
                                </label> @:&nbsp;&nbsp;
                                    
                                @: </td>
                            }
                            @:</tr>
                            
                        }
                    </table>
                </div>
            </div>
      
        <br />
        <div class="form-group">
            
            <div class="col-lg-5">
      
            <label class="control-label col-lg-3 col-md-3 col-sm-8 col-xs-12">Add New Documents</label>

                <label class="control-label col-md-8">
                    <input type="file" class="" name="Attachments" multiple="multiple" /><br />
                </label>
            </div>
        </div>
    </div>
    </div>


<br />
        <div class="form-group">
            <div class="col-md-offset-3 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary col-lg-2" />
                @Html.ActionLink("Cancel", "Index", "Postings", null, new { @class = "btn btn-primary col-lg-2 col-md-offset-2" })
            </div>
        </div>
}


 


    @*<div>
        @Html.ActionLink("Cancel", "Index", "Postings")
    </div>*@

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Views/Applications/Delete.cshtml
@model CommunityProject_ProjectUnity.Models.Application

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Application</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Applicant.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Applicant.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Posting.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Posting.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Views/Applications/Details.cshtml
@model CommunityProject_ProjectUnity.Models.Application

@{
    ViewBag.Title = "Details";
}
<div class="row">
    <h2>Application Details</h2>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Applicant.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Applicant.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Posting.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Posting.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>


    </dl>
    <div class="form-group">
        <label class="control-label col-md-5"> Attached Documents:</label>
        <div class="col-md-10">
            @foreach (var doc in Model.UserFiles)
            {

                @doc.fileName @:&nbsp;
                @Html.ActionLink("Download File", "Download", new { id = doc.ID })<br />

            }
            @foreach(var doc in ViewBag.Files)
            {
                 @doc.fileName @:&nbsp;
                @Html.ActionLink("Download File", "Download", new { id = doc.ID })<br />
            }
        </div>
    </div>
    <br />

    <div class="col-lg-5">
        @{
            var postype = Model.Posting.PositionType;
            int matchcount = 0;
            int skcount = 0;
            if (postype == "Non-Teaching")
            {

                <label class="control-label col-md-7">Required Skills:</label>

                <div class="well">
                    @{

                        foreach (var skill in Model.Posting.Skills)
                        {

                            <br />

                            @skill.SkillName;
                            skcount += 1;

                        }
                    }

                </div>




                <label class="control-label col-md-7">Applicant's Skills:</label>

                <div class="well">
                    @{
                        int apcount = 0;
                        foreach (var skill in Model.Applicant.Skills)
                        {

                            <br />
                            @skill.SkillName;
                            apcount += 1;

                        }
                    }

                </div>


                <label class="control-label col-md-7">Matching Skills:</label>
                <div class="well">
                    @{

                        foreach (var skill in Model.Posting.Skills)
                        {
                            var pskillid = skill.ID;
                            foreach (var apskill in Model.Applicant.Skills)
                            {
                                var apskillid = apskill.ID;
                                if (apskillid == pskillid)
                                {
                                    <br />
                                    @apskill.SkillName;
                                    matchcount += 1;
                                }
                            }
                        }
                    }



                </div>

                        }
                        else
                        {
          
                                <label class="control-label col-md-7">Required Qualifications:</label>

                                <div class="well">
                                    @{

                                        foreach (var skill in Model.Posting.Qualifications)
                                        {

                                            <br />

                                            @skill.Name;
                                            skcount += 1;

                                        }
                                    }

                                </div>




                                <label class="control-label col-md-7">Applicant's Qualifications:</label>

                                <div class="well">
                                    @{
                                        int apcount = 0;
                                        foreach (var skill in Model.Applicant.Qualifications)
                                        {

                                            <br />
                                            @skill.Name;
                                            apcount += 1;

                                        }
                                    }

                                </div>


                                <label class="control-label col-md-7">Matching Qualifications:</label>
                                <div class="well">
                                    @{

                                        foreach (var skill in Model.Posting.Qualifications)
                                        {
                                            var pskillid = skill.ID;
                                            foreach (var apskill in Model.Applicant.Qualifications)
                                            {
                                                var apskillid = apskill.ID;
                                                if (apskillid == pskillid)
                                                {
                                                    <br />
                                                    @apskill.Name;
                                                    matchcount += 1;
                                                }
                                            }
                                        }
                                    }


                                </div>
                           

                                }
                                }
                            </div>

    <div class="col-md-5">
       
        @if (User.IsInRole("Admin"))
        {
            
            int percent = (int)Math.Round((double)(100 * matchcount) / skcount); ;


        
            if (percent >= 50)
            {

                <img src="@Url.Content("~/Images/green.png")" alt="green" />
            }
            else
            {
                <img src="@Url.Content("~/Images/red.png")" alt="red" />
            }
                     <h2><label class="control-label"> Match Percentage:</label>@percent%<br /></h2>
        }
        

    </div>
</div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")|
        @Html.ActionLink("Download", "PrintPDF", new { id = Model.ID })

    </p>

CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Views/Applications/Index.cshtml
@model IEnumerable<CommunityProject_ProjectUnity.Models.Application>

@{
    ViewBag.Title = "Applications List";
}
<link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" 

              rel="stylesheet" type="text/css" media="all" />
        <link href="@Url.Content("~/Content/themes/smoothness/jquery-ui-1.7.2.custom.css")" 

              rel="stylesheet" type="text/css" media="all" />
        <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" 

              type="text/javascript"></script>
       
        <script src="@Url.Content("~/Scripts/jquery.jeditable.js")" 

              type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery-ui.js")" 

              type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery.validate.js")" 

              type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery.dataTables.editable.js")" 

              type="text/javascript"></script>
<link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<div class="row">
   
        <div class="panel panel-primary list-panel" id="list-panel">
            <div class="panel-heading list-panel-heading">
                <h1 class="panel-title list-panel-title">Applications</h1>
            </div>
            <div class="well">
                <div class="panel-body">
                    <table id="applications-data-table"
                           class="table table-striped table-bordered"
                           style="width:100%">
                        <thead>
                            <tr>
                                <th>Applicant Name</th>
                                <th>Posting Name</th>
                                <th>Comments</th>
                                <th>Closing Date</th>

                                <th>View More Details</th>
                                <th>Edit</th>
                                <th>Download Application</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>@item.Applicant.FormalName</td>
                                <td>@item.Posting.Name</td>
                                <td>@item.Comments</td>
                                <td>@item.Posting.ClosingDate</td>
                                


                                <td>
                                    @Html.ActionLink("Details", "Details", "Applications", new { id = item.ID }, null)

                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", "Applications", new { id = item.ID }, null)
                                </td>
                                <td>
                                    @Html.ActionLink("Download", "PrintPDF", new { id = item.ID })
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
  
</div>
 @section Scripts
{
            <script type="text/javascript">
                $(function () {
                    $('#applications-data-table').DataTable({
                        "pageLength": 50,
                        language: {
                            searchPlaceholder: "Type here to Search"
                        }
                    });
                });
            </script>
        }

    

CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Views/Applications/SelectedApplications.cshtml
@model IEnumerable<CommunityProject_ProjectUnity.Models.Application>
@{
    ViewBag.Title = "Selected Applications";
}

<link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

<h2>Selected Applications</h2>


<div class="container-fluid">
    <div class="col-md-12">
        <table id="dataTable" class="table table-striped table-bordered nowrap" cellspacing="0">
            <thead>
                <tr>
                    <th>Applicant Name</th>
                    <th>Job Posting</th>
                    <th>Posting Closing Date</th>
                    <th>Schools</th>
                    <th>FTE</th>
                    <th>Salary</th>
                    <th>Openings</th>
                   
                </tr>
            </thead>
            <tbody>
                @foreach (var app in Model)
                {
                    <tr>
                        <td>@app.Applicant.FullName</td>
                        <td>@app.Posting.Name</td>
                        <td>@app.Posting.ClosingDate</td>
                        <td>
                            @foreach (var school in app.Posting.Schools)
                            {
                                @school.Name<br />
                            }


                        </td>

                        
                        <td>@app.Posting.FTE</td>
                        <td>@app.Posting.Salary</td>
                        <td>@app.Posting.Openings</td>
                        
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
        

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#dataTable').DataTable({
                "pageLength": 50,
                language: {
                    searchPlaceholder: "Type here to Search"
                }

            });
        });
    </script>
}