CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Models/Position.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CommunityProject_ProjectUnity.Models
{
    public class Position : Auditable
    {
        public Position()
        {
            this.Postings = new HashSet<Posting>();
            this.Skills = new HashSet<Skill>();
            this.Qualifications = new HashSet<Qualification>();

        }
        public int ID { get; set; }

        [Required(ErrorMessage = "Position Name Required")]
        [Display(Name = "Position Name")]
        [StringLength(50, ErrorMessage = "Position Name Must Be Shorter Than 50 Characters")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Position Description Required")]
        [Display(Name = "Description")]
        [StringLength(1200, ErrorMessage = "Position Description Must Be Shorter Than 1200 Characters")]
        public string PositionDescription { get; set; }


        [Required(ErrorMessage = "Salary Type Required")]
        [Display(Name = "Salary Type")]
        public string SalaryType { get; set; }

        [Required(ErrorMessage = "Salary Required")]
        [Display(Name = "Salary")]
        [Range(0.01, 999999.99, ErrorMessage = "Position Salary must be between $0.01 and $999999.99")]
        [DataType(DataType.Currency)]
        public int PositionSalary { get; set; }

        [Required(ErrorMessage = "Job Code is Required")]
        [Display(Name = "Job Code")]
        [StringLength(10, ErrorMessage = "Job Code cannot be more than  10 Characters")]
        [Index("IX_Unique_JobCode", IsUnique = true)]
        public string JobCode { get; set; }

        [Required(ErrorMessage = "Position Type is Required")]
        public string PositionType { get; set; }

        public virtual ICollection<Qualification> Qualifications { get; set; }

        public virtual ICollection<Skill> Skills { get; set; }

        [Display(Name = "Position")]
        public string JobCodeName
        {
            get
            {
                return JobCode + "-" + Name;
            }
            
        }


        public virtual ICollection<Posting> Postings { get; set; }
    }
}

CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Controllers/PositionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CommunityProject_ProjectUnity.DAL;
using CommunityProject_ProjectUnity.Models;
using System.Data.Entity.Infrastructure;
using CommunityProject_ProjectUnity.ViewModels;

namespace CommunityProject_ProjectUnity.Controllers
{
   
    public class PositionsController : Controller
    {
        private ProjectUnityEntities db = new ProjectUnityEntities();

        // GET: Positions
        public ActionResult Index()
        {
            PopulateDropDownLists();
            var positions = db.Positions;
                

            return View(positions.ToList());
        }

        // GET: Positions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // GET: Positions/Create
        public ActionResult Create()
        {
            var position = new Position();
            PopulateDropDownLists();
            var postype = position.PositionType;
            if (postype == "Non-Teaching")
            {
                PopulateAssignedSkillData(position);
            }
            if (postype == "Teaching")
            {
                PopulateAssignedQualificationData(position);
            }
            PopulateAssignedSkillData(position);
            PopulateCreateQualificationData(position);


            return View();
        }

        // POST: Positions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,PositionDescription,PositionSalary,SalaryType,JobCode,PositionType,CreatedBy,CreatedOn,UpdatedBy,UpdatedOn,RowVersion")] Position position, string[] selectedOptions, string[] selectedqualOptions)
        {

            try
            {

                if (selectedOptions != null)
                {
                    position.Skills = new List<Skill>();
                    foreach (var skill in selectedOptions)
                    {
                        var skillToAdd = db.Skills.Find(int.Parse(skill));
                        position.Skills.Add(skillToAdd);
                    }
                }


                if (selectedqualOptions != null)
                {
                    position.Qualifications = new List<Qualification>();
                    foreach (var qual in selectedqualOptions)
                    {
                        var qualToAdd = db.Qualifications.Find(int.Parse(qual));
                        position.Qualifications.Add(qualToAdd);
                    }
                }

                if (ModelState.IsValid)
                {
                    db.Positions.Add(position);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }




              
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            ViewBag.PositionID = new SelectList(db.Skills, "ID", "Name", position.ID);
            PopulateDropDownLists(position);
            PopulateAssignedQualificationData(position);
            PopulateAssignedSkillData(position);
            return View(position);
        }

        // GET: Positions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            var postype = position.PositionType;
            if (postype == "Non-Teaching")
            {
                PopulateAssignedSkillData(position);
            }
            if (postype == "Teaching")
            {
                PopulateAssignedQualificationData(position);
            }
            PopulateDropDownLists();

            return View(position);
        }

        // POST: Positions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int? id, Byte[] rowVersion, string[] selectedOptions)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var positionToUpdate = db.Positions.Find(id);
            if (TryUpdateModel(positionToUpdate, "",
               new string[] { "PositionName", "PositionDescription", "PositionSalary", "JobCode","PositionType" }))
            {

                try
                {
                    var positype = db.Postings.Where(p => p.ID == id)
                                   .Select(q => q.PositionType)
                                   .FirstOrDefault();
                    if (positype == "Non-Teaching")
                    {
                        UpdatePositionSkills(selectedOptions, positionToUpdate);
                    }
                    if (positype == "Teaching")
                    {
                        UpdatePositionQualifications(selectedOptions, positionToUpdate);
                    }

                    db.Entry(positionToUpdate).OriginalValues["RowVersion"] = rowVersion;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException ex)// Added for concurrency
                {
                    var entry = ex.Entries.Single();
                    var clientValues = (Position)entry.Entity;
                    var databaseEntry = entry.GetDatabaseValues();
                    if (databaseEntry == null)
                    {
                        ModelState.AddModelError("",
                            "Unable to save changes. The Position was deleted by another user.");
                    }
                    else
                    {
                        var databaseValues = (Position)databaseEntry.ToObject();
                        if (databaseValues.Name != clientValues.Name)
                            ModelState.AddModelError("PositionName", "Current value: "
                                + databaseValues.Name);
                        if (databaseValues.PositionDescription != clientValues.PositionDescription)
                            ModelState.AddModelError("PositionDescription", "Current value: "
                                + databaseValues.PositionDescription);
                        if (databaseValues.PositionSalary != clientValues.PositionSalary)
                            ModelState.AddModelError("PositionSalary", "Current value: "
                                + String.Format("{0:c}", databaseValues.PositionSalary));
                        
                       
                        ModelState.AddModelError(string.Empty, "The record you attempted to edit "
                                + "was modified by another user after you received your values. The "
                                + "edit operation was canceled and the current values in the database "
                                + "have been displayed. If you still want to save your version of this record, click "
                                + "the Save button again. Otherwise click the 'Back to List' hyperlink.");
                        positionToUpdate.RowVersion = databaseValues.RowVersion;
                    }
                }
                catch (DataException)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                }
            }
            PopulateDropDownLists(positionToUpdate);
            var postype = db.Postings.Where(p => p.ID == id)
                                   .Select(q => q.PositionType)
                                   .FirstOrDefault();
            if (postype == "Non-Teaching")
            {
                PopulateAssignedSkillData(positionToUpdate);
            }
            if (postype == "Teaching")
            {
                PopulateAssignedQualificationData(positionToUpdate);
            }
            return View(positionToUpdate);
        }

        // GET: Positions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // POST: Positions/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Position position = db.Positions.Find(id);
        //    try
        //    {
        //        db.Positions.Remove(position);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    catch (DataException dex)
        //    {

CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Views/Positions/Create.cshtml
@model CommunityProject_ProjectUnity.Models.Position

@{
    ViewBag.Title = "Create";
}

<h2>Create Position</h2>
<script src="@Url.Content("~/Scripts/jquery.min.js")" type="text/javascript"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js"></script>
<script type="text/javascript">
    @*<script src="~/Scripts/PositionCreate.js"></script>*@
    $(function () {

        $("#PositionType").change(function () {

            var selectedItemValue = $(this).val();

            if (selectedItemValue == "Teaching") {
                $('#quallist').removeClass();
            }
            else {
                $('#quallist').addClass("invisible");
                $('skilldiv').removeClass();
            }
            if (selectedItemValue == "Non-Teaching") {

                $('#skilldiv').removeClass();
            }
            else {
                $('skilldiv').addClass("invisible");
                $('#quallist').removeClass();
            }

        });
    });
</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PositionType, "Job Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PositionType", null, "Select the Job Type", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PositionType, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.JobCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobCode, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PositionDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PositionDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PositionDescription, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.SalaryType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SalaryType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SalaryType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PositionSalary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PositionSalary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PositionSalary, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div id="skilldiv" class="invisible">
                <div class="col-md-2">&nbsp;</div>
                <div class="form-group col-md-4">
                    <label class="control-label" id="availlabel">Available Skills:</label><br />
                    @Html.ListBox("availOptions", (MultiSelectList)ViewBag.availOpts, new { @class = "form-control" })
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <button type="button" id="btnLeftSkill" class="btn  btn-primary  btn-group-lg">
                            <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
                        </button>
                    </div>
                    <div class="form-group">
                        <button type="button" id="btnRightSkill" class="btn btn-default btn-group-lg">
                            <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                        </button>
                        <div></div>
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label" id="selectlabel">Skills Assigned:</label><br />
                    @Html.ListBox("selectedOptions", (MultiSelectList)ViewBag.selOpts, new { @class = "form-control" })

                </div>
            </div>

        </div>

        <div class="row">
            <div id="quallist" class="invisible">
                <div class="col-md-2">&nbsp;</div>
                <div class="form-group col-md-4">
                    <label class="control-label" id="availlabel">Available Qualifiations:</label><br />
                    @Html.ListBox("availqualOptions", (MultiSelectList)ViewBag.availqualOpts, new { @class = "form-control" })
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <button type="button" id="btnLeftQ" class="btn  btn-primary  btn-group-lg">
                            <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
                        </button>
                    </div>
                    <div class="form-group">
                        <button type="button" id="btnRightQ" class="btn btn-default btn-group-lg">
                            <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                        </button>
                        <div></div>
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label" id="selectlabel">Qualifications Assigned:</label><br />
                    @Html.ListBox("selectedqualOptions", (MultiSelectList)ViewBag.selqualOpts, new { @class = "form-control" })

                </div>
            </div>

        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="btnPSubmit" value="Create" class="btn btn-primary btn col-lg-2" />
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-primary col-lg-2 col-md-offset-2" })
            </div>
        </div>
    </div>
    <table class="model-state">
        @foreach (var item in ViewContext.ViewData.ModelState)
        {
            if (item.Value.Errors.Any())
            {
                <tr>
                    <td><b>@item.Key</b></td>
                    <td>@((item.Value == null || item.Value.Value == null) ? "<null>" : item.Value.Value.RawValue)</td>
                    <td>@(string.Join("; ", item.Value.Errors.Select(x => x.ErrorMessage)))</td>
                </tr>
            }
        }
    </table>
}

@*<div>
        @Html.ActionLink("Cancel", "Index")
    </div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/PositionSkills")

}

CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Views/Positions/Edit.cshtml
@model CommunityProject_ProjectUnity.Models.Position

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Position</h2>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js"></script>
@*<script type="text/javascript">

        $(function () {
            if ($("#PositionType").val() == '0') {
                var jobDefaultValue = "<optipn value='0' >--Select a Job Type--</option>"
                $("#JobCode").html(jobDefaultValue).show();
            }
            $("#PositionType").change(function () {
                var selectedItemValue = $(this).val();

                var ddlJobcode = $("#JobCode");
                $.ajax({
                    cache: false,
                    type: "GET",
                    url: '@Url.Action("GetJobCodeByPositionType", "Positions")',
                    data: { "ID": selectedItemValue },
                    success: function (data) {
                        ddlJobcode.html('');
                        $.each(data, function (id, option) {
                            ddlJobcode.append($('<option></option>').val(option.id).html(option.name));
                        });
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert('Found error.');
                    }
                });
            });
        });
    </script>*@

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="row">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)
            @Html.HiddenFor(model => model.RowVersion)
            <div class="col-lg-6 col-md-6 col-sm-10 col-xs-12">
                <div class="form-group">
                    @Html.LabelFor(model => model.PositionType, "Job Type", htmlAttributes: new { @class = "control-label col-lg-3 col-md-3 col-sm-8 col-xs-12" })
                    <div class="col-lg-5 col-md-5 col-sm-10 col-xs-12">
                        @Html.DropDownList("PositionType", null, "Select the Job Type", htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.PositionType, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.JobCode, htmlAttributes: new { @class = "control-label col-lg-3 col-md-3 col-sm-8 col-xs-12" })
                    <div class="col-lg-5 col-md-5 col-sm-10 col-xs-12">
                        @Html.EditorFor(model => model.JobCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.JobCode, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-lg-3 col-md-3 col-sm-8 col-xs-12" })
                    <div class="col-lg-5 col-md-5 col-sm-10 col-xs-12">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-md-6 col-sm-10 col-xs-12">
                <div class="form-group">
                    @Html.LabelFor(model => model.PositionDescription, htmlAttributes: new { @class = "control-label col-lg-3 col-md-3 col-sm-8 col-xs-12" })
                    <div class="col-lg-5 col-md-5 col-sm-10 col-xs-12">
                        @Html.TextAreaFor(model => model.PositionDescription, htmlAttributes: new { @class = "form-control", @rows = 5, style = "width: 700px;, control-label" })
                        @Html.ValidationMessageFor(model => model.PositionDescription, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PositionSalary, htmlAttributes: new { @class = "control-label col-lg-3 col-md-3 col-sm-8 col-xs-12" })
                    <div class="col-lg-5 col-md-5 col-sm-10 col-xs-12">
                        @Html.EditorFor(model => model.PositionSalary, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PositionSalary, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-horizontal">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-10 col-xs-12">
                <div class="form-group">
                    <label class="control-label col-lg-3 col-md-3 col-sm-8 col-xs-12" id="availlabel">Available Skills/Qualifications:</label><br />
                    <div class="col-lg-5 col-md-5 col-sm-10 col-xs-12">
                        @Html.ListBox("availOptions", (MultiSelectList)ViewBag.availOpts, new { @class = "form-control", style = "width: 700px;, control-label" })
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <button type="button" id="btnLeftSkill" class="btn  btn-primary  btn-group-lg col-md-offset-9">
                                <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
                            </button>
                        </div>
                        <div class="form-group">
                            <button type="button" id="btnRightSkill" class="btn btn-default btn-group-lg col-md-offset-9">
                                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-10 col-xs-12">
                <div class="form-group">
                    <label class="control-label col-lg-3 col-md-3 col-sm-8 col-xs-12" id="selectlabel">Skills/Qualifications Assigned:</label><br />
                    <div class="col-lg-5 col-md-5 col-sm-10 col-xs-12">
                        @Html.ListBox("selectedOptions", (MultiSelectList)ViewBag.selOpts, new { @class = "form-control", style = "width: 700px;, control-label" })
                    </div>
                </div>
            </div>


            <div class="col-lg-12 col-md-6 col-sm-10 col-xs-12">
                <div class="form-group">
                    <div class="col-md-offset-3">
                        <input type="submit" id="btnPSubmit" value="Save" class="btn btn-primary col-lg-2" />
                        @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-primary col-lg-2 col-md-offset-2" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@*<div>
        @Html.ActionLink("Cancel", "Index")
    </div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/PositionSkills")
}

CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Views/Positions/Index.cshtml
@model IEnumerable<CommunityProject_ProjectUnity.Models.Position>

@{
    ViewBag.Title = "Positions List";
}

<h2>Positions</h2>
<link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" 

              rel="stylesheet" type="text/css" media="all" />
        <link href="@Url.Content("~/Content/themes/smoothness/jquery-ui-1.7.2.custom.css")" 

              rel="stylesheet" type="text/css" media="all" />
        <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" 

              type="text/javascript"></script>
       
        <script src="@Url.Content("~/Scripts/jquery.jeditable.js")" 

              type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery-ui.js")" 

              type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery.validate.js")" 

              type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery.dataTables.editable.js")" 

              type="text/javascript"></script>
<link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
</p>
<div class="row">
   
        <div class="panel panel-primary list-panel" id="list-panel">
            <div class="panel-heading list-panel-heading">
                <h1 class="panel-title list-panel-title">Positions</h1>
            </div>
            <div class="well">
                <div class="panel-body">
                    <table id="positions-data-table"
                           class="table table-striped table-bordered"
                           style="width:100%">
                        <thead>
                            <tr>
                                <th>Position Type</th>
                                <th>Job Code</th>
                                <th>Name</th>
                                <th>Salary</th>
                                <th>Edit Position</th>
                                <th>View More Details</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var position in Model)
                            {
                                <tr>
                                    <td>@position.PositionType</td>
                                    <td>@position.JobCodeName</td>
                                    <td>@position.Name</td>
                                    <td>$@position.PositionSalary</td>
                                    
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", "Positions", new { id = position.ID }, null)

                                    </td>
                                    <td>
                                        @Html.ActionLink("Details", "Details", "Positions", new { id = position.ID }, null)

                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
  
</div>
 @section Scripts
{
            <script type="text/javascript">
                $(function () {
                    $('#positions-data-table').DataTable({

                        "pageLength": 50,
                        language: {
                            searchPlaceholder: "Type here to Search"
                        }
                    });
                });
            </script>
        }